# Julia exercise list 01

### Construa uma funcão que determine qual é a coluna vencedora. Para cada linha da matriz entrada esta função atribui valor igual a um para o maior elemento da linha e zero para o menor elemento. Em caso de valores iguais, a primeira coluna recebe valor igual a um e a segunda coluna valor igual a zero. A funcão deve ser construida de forma a suportar matrizes de entrada de qualquer dimensões (n x m).

In [1]:
function winnerColumn(matrix)
    lineSize = size(matrix,1)
    columnSize = size(matrix,2)
    result = Array{Int64}(lineSize, columnSize)
    for line=1:lineSize
        maxIndex = findmax(matrix[line,:])[2]
        r = zeros(columnSize)
        r[maxIndex] = 1
        result[line,:] = r
    end
    result
end
randMatrix = [rand(1:5) for x in 1:3, y in 1:3]
println("to matrix: ")
print(randMatrix)
winnerColumn(randMatrix)

to matrix: 
[5 3 5
 5 3 3
 1 2 4]

3x3 Array{Int64,2}:
 1  0  0
 1  0  0
 0  0  1

### Dada a matriz M = [5 10 -5 22; 1 33 15 3; 8 29 12 1; 3 11 39 20]; substitua os 3 maiores elementos por zero.

In [2]:
function elementsToZero(matrix, n)
    for index=1:n
        indexToZero = findmax(matrix)[2]
        matrix[indexToZero] = 0
    end
    matrix
end
randMatrix = [rand(1:5) for x in 1:3, y in 1:3]
println("to matrix: ")
print(randMatrix)
elementsToZero(randMatrix, 3)

to matrix: 
[2 1 5
 3 3 5
 1 4 3]

3x3 Array{Int64,2}:
 2  1  0
 3  3  0
 1  0  3

### Crie uma função que receba uma matriz com valores aleatórios e torne a média e o desvio padrão de cada coluna iguais a zero e a um, respectivamente

In [3]:
function matrixParser(matrix)
    for column=1:size(matrix, 2)
        matrix[:,column] -= matrix[:,column][end:-1:1]
    end
    matrix
end

randMatrix = [rand(1:10) for x in 1:5, y in 1:3]
println("to matrix: ")
print(randMatrix)
matrixParser(randMatrix)

to matrix: 
[3 6 8
 10 9 5
 5 2 1
 5 5 5
 8 4 2]

5x3 Array{Int64,2}:
 -5   2   6
  5   4   0
  0   0   0
 -5  -4   0
  5  -2  -6

### Faça uma amostragem de tamanho 500 do intervalo –2 a 2 uniformemente distribuída, calcule o seno, o coseno, 1/seno e 1/coseno, e, utilizando as funções plot e subplot, mostre os gráficos das funções das seguintes formas: todos juntos no mesmo par de eixos (plot) e separados na mesma janela (subplot).

In [10]:
using Plots
plotly()
baseArr = linspace(-2, 2, 500)
arr = [[sin(x), cos(x), 1/sin(x), 1/cos(x)] for x in baseArr]
seno = [x[1] for x in arr]
cose = [x[2] for x in arr]
revSen = [x[3] for x in arr]
revCos = [x[4] for x in arr]
matrix = reshape([seno; cose; revSen; revCos],500,4)
plot(baseArr, matrix)

0.004008005301149225(249.50066800392395,251)