# Julia exercise list 01

### Construa uma funcão que determine qual é a coluna vencedora. Para cada linha da matriz entrada esta função atribui valor igual a um para o maior elemento da linha e zero para o menor elemento. Em caso de valores iguais, a primeira coluna recebe valor igual a um e a segunda coluna valor igual a zero. A funcão deve ser construida de forma a suportar matrizes de entrada de qualquer dimensões (n x m).

In [95]:
function winnerColumn(matrix)
    lineSize = size(matrix,1)
    columnSize = size(matrix,2)
    result = Array{Int64}(lineSize, columnSize)
    for line=1:lineSize
        maxIndex = findmax(matrix[line,:])[2]
        r = zeros(columSize)
        r[maxIndex] = 1
        result[line,:] = r
    end
    result
end
randMatrix = [rand(1:5) for x in 1:3, y in 1:3]
println("to matrix: ")
print(randMatrix)
winnerCollum(randMatrix)

to matrix: 
[2 5 5
 5 4 1
 1 3 1]

3x3 Array{Int64,2}:
 0  1  0
 1  0  0
 0  1  0

### Dada a matriz M = [5 10 -5 22; 1 33 15 3; 8 29 12 1; 3 11 39 20]; substitua os 3 maiores elementos por zero.

In [111]:
function elementsToZero(matrix, n)
    for index=1:n
        indexToZero = findmax(matrix)[2]
        matrix[indexToZero] = 0
    end
    matrix
end
randMatrix = [rand(1:5) for x in 1:3, y in 1:3]
println("to matrix: ")
print(randMatrix)
elementsToZero(randMatrix, 3)

to matrix: 
[3 4 3
 3 1 2
 2 5 1]

3x3 Array{Int64,2}:
 0  0  3
 3  1  2
 2  0  1

### Crie uma função que receba uma matriz com valores aleatórios e torne a média e o desvio padrão de cada coluna iguais a zero e a um, respectivamente

In [130]:
function matrixParser(matrix)
    for column=1:size(matrix, 2)
        matrix[:,column] -= matrix[:,column][end:-1:1]
    end
    matrix
end

randMatrix = [rand(1:10) for x in 1:5, y in 1:3]
println("to matrix: ")
print(randMatrix)
matrixParser(randMatrix)

to matrix: 
[7 4 4
 6 2 4
 2 6 2
 5 1 7
 8 1 7]

5x3 Array{Int64,2}:
 -1   3  -3
  1   1  -3
  0   0   0
 -1  -1   3
  1  -3   3